USERNAME_MIN_LENGTH = 5
USERNAME_MAX_LENGTH = 64
USERNAME_PATTERN = r"^[a-zA-Z0-9_-]+$"

PASSWORD_MIN_LENGTH = 6
PASSWORD_MAX_LENGTH = 128

PROVIDER_SUBJECT_MAX_LENGTH = 255
PASSWORD_HASH_MAX_LENGTH=512
