from typing import Protocol
from uuid import UUID


class TokenServiceProtocol(Protocol):
    """Contract for token engines. Verification always returns the user_id."""

    def create_activation_token(self, user_id: UUID) -> str: ...

    def create_access_token(self, user_id: UUID) -> str: ...

    def create_refresh_token(self, user_id: UUID) -> str: ...

    def verify_activation_token(self, token: str) -> UUID: ...

    def verify_access_token(self, token: str) -> UUID: ...

    def verify_refresh_token(self, token: str) -> UUID: ...
