[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fastapi-auth-lib"
version = "0.1.4"
description = "Authentication library for FastAPI"
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "Zoltán M.", email = "ego.pressure@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
#addopts = [
#    "--cov-reset",
#    "--cov=fastapi_auth_lib",
#    "--cov-fail-under=80",
#    "--cov-report=term-missing"
#]

pythonpath = "src"
testpaths = "tests"
asyncio_mode = "auto"
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
